AWSTemplateFormatVersion: "2010-09-09"

Resources:

  FirehoseLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: firehose-logs
      RetentionInDays: 7

  OpenSearchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: open-search-logs
      RetentionInDays: 7

  ApplicationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: application-logs
      RetentionInDays: 7
      
  OpenSearchLogGroupPolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: OpenSearchLogGroupPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: es.amazonaws.com
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !Sub "${LogGroupArn}/*"
              Parameters:
                LogGroupArn: !GetAtt OpenSearchLogGroup.Arn

  FirehoseLogGroupPolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: FirehoseLogGroupPolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: !Sub "${LogGroupArn}/*"
              Parameters:
                LogGroupArn: !GetAtt FirehoseLogGroup.Arn


Outputs:
  FirehoseLogGroupName:
    Value: !Ref FirehoseLogGroup
  FirehoseLogGroupArn:
    Value: !GetAtt FirehoseLogGroup.Arn

  OpenSearchLogGroupName:
    Value: !Ref OpenSearchLogGroup
  OpenSearchLogGroupArn:
    Value: !GetAtt OpenSearchLogGroup.Arn

  ApplicationLogGroupName:
    Value: !Ref ApplicationLogGroup
  ApplicationLogGroupArn:
    Value: !GetAtt ApplicationLogGroup.Arn



