AWSTemplateFormatVersion: "2010-09-09"
Resources:
  FirehoseLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: open-search-logs
      RetentionInDays: 7
      
  FirehoseLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref FirehoseLogGroup
      LogStreamName: FirehoseStreamLogs
      
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: openserach-lambda-logs
      RetentionInDays: 7

  OpenSearchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: open-search-logs
      RetentionInDays: 7
      
  OpenSearchLogStream:
    Type: AWS::Logs::LogStream
    Properties:
      LogGroupName: !Ref OpenSearchLogGroup
      LogStreamName: OpenSearchStreamLogs
      
  ApplicationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: application-logs
      RetentionInDays: 7

  OpenSearchLogGroupPolicy:
    Type: AWS::Logs::ResourcePolicy
    Properties:
      PolicyName: OpenSearchLogGroupPolicy
      PolicyDocument: !Sub |
        {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Effect": "Allow",
              "Principal": {
                "Service": "es.amazonaws.com"
              },
              "Action": [
                "logs:CreateLogStream",
                "logs:PutLogEvents"
              ],
              "Resource": [
                "${OpenSearchLogGroup.Arn}",
                "${OpenSearchLogGroup.Arn}:*"
              ]
            }
          ]
        }

Outputs:
  FirehoseLogGroupName:
    Value: !Ref FirehoseLogGroup
  FirehoseLogStreamName:
    Value: !Ref FirehoseLogStream
  LambdaLogGroupName:
    Value: !Ref LambdaLogGroup
  LambdaLogGroupArn:
    Value: !GetAtt LambdaLogGroup.Arn
  OpenSearchLogGroupName:
    Value: !Ref OpenSearchLogGroup
  OpenSearchLogGroupArn:
    Value: !GetAtt OpenSearchLogGroup.Arn
  ApplicationLogGroupName:
    Value: !Ref ApplicationLogGroup
  ApplicationLogGroupArn:
    Value: !GetAtt ApplicationLogGroup.Arn




