AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  LambdaFunction:
    Type: String
    
  ApplicationLogGroup:
    Type: String

Resources:

  CloudWatchToLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudWatchToLambda
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: logs.amazonaws.com
            Action: sts:AssumeRole

      Policies:
        - PolicyName: InvokeLambdaPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource: !Ref LambdaFunction

  LogSubscriptionFilter:
    Type: AWS::Logs::SubscriptionFilter
    Properties:
      LogGroupName: !Ref ApplicationLogGroup
      FilterPattern: ""
      DestinationArn: !Ref LambdaFunction
      RoleArn: !GetAtt CloudWatchToLambdaRole.Arn

