AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  OpenSearchDomain:
    Type: String

  FirehoseLogGroup:
    Type: String

  FirehoseLogStream:
    Type: String

  OpenSearchFirehoseRole:
    Type: String

  FirehoseTransformLambdaArn:
    Type: String

  FirehoseTransformLambdaName:
    Type: String
    
Resources:
  LogsBackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-logs-backup-bucket"

  FirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: FirehoseRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: FirehoseS3Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:GetBucketLocation"
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                Resource: 
                  - !GetAtt LogsBackupBucket.Arn
                  - !Sub "${LogsBackupBucket.Arn}/*"

  FirehoseStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: log-delivery-stream
      DeliveryStreamType: DirectPut
      AmazonopensearchserviceDestinationConfiguration:
        DomainARN: !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${OpenSearchDomain}"
        IndexName: application-logs
        RoleARN: !Ref OpenSearchFirehoseRole
        S3Configuration:
          BucketARN: !GetAtt LogsBackupBucket.Arn
          RoleARN: !GetAtt FirehoseRole.Arn
        CloudWatchLoggingOptions:
           Enabled: true
           LogGroupName: !Ref FirehoseLogGroup
           LogStreamName: !Ref FirehoseLogStream
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 1
          
Outputs: 
  FirehoseDeliveryStreamName:
    Value: !Ref FirehoseStream
  FirehoseDeliveryStreamArn:
    Value: !GetAtt FirehoseStream.Arn
