AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  OpenSearchDomain:
    Type: String

  FirehoseLogGroup:
    Type: String

  FirehoseLogStream:
    Type: String
    
Resources:
  LogsBackupBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-logs-backup-bucket"

  FirehoseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: FirehoseToOpenSearchPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "es:ESHttpGet"
                  - "es:ESHttpPost"
                  - "es:ESHttpPut"
                  - "es:DescribeElasticsearchDomain"
                Resource: !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${OpenSearchDomain}/*"
              - Effect: Allow
                Action:
                  - "s3:ListBucket"
                  - "s3:GetBucketLocation"
                  - "s3:PutObject"
                  - "s3:PutObjectAcl"
                Resource: !Sub "${LogsBackupBucket.Arn}/*"
                
              - Effect: Allow
                Action:
                  - "logs:PutLogEvents"
                  - "logs:CreateLogStream"
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${FirehoseLogGroup}:*"

  FirehoseStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: log-delivery-stream
      DeliveryStreamType: DirectPut
      AmazonopensearchserviceDestinationConfiguration:
        DomainARN: !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${OpenSearchDomain}"
        IndexName: application-logs
        RoleARN: !GetAtt FirehoseRole.Arn
        S3Configuration:
          BucketARN: !GetAtt LogsBackupBucket.Arn
          RoleARN: !GetAtt FirehoseRole.Arn
        CloudWatchLoggingOptions:
          Enabled: true
          LogGroupName: !Ref FirehoseLogGroup
          LogStreamName: !Ref FirehoseLogStream
        BufferingHints:
          IntervalInSeconds: 300
          SizeInMBs: 5

Outputs: 
  FirehoseDeliveryStreamName:
    Value: !Ref FirehoseStream
  FirehoseDeliveryStreamArn:
    Value: !GetAtt FirehoseStream.Arn





