AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  OpenSearchLogGroup:
    Type: String

Resources:

  OpenSearchDomain:
    Type: AWS::OpenSearchService::Domain
    Properties:
      DomainName: logs-domain
      EngineVersion: OpenSearch_2.11
      ClusterConfig:
        InstanceType: t3.small.search
        InstanceCount: 1
        
      LogPublishingOptions:
        ES_APPLICATION_LOGS:
          CloudWatchLogsLogGroupArn: !Ref OpenSearchLogGroup
          Enabled: true

      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10

      NodeToNodeEncryptionOptions:
        Enabled: true

      EncryptionAtRestOptions:
        Enabled: true

      DomainEndpointOptions:
        EnforceHTTPS: true

      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: "{{resolve:ssm:/OpenSearch/Username}}"
          MasterUserPassword: "{{resolve:ssm:/OpenSearch/Password}}"

      AccessPolicies:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action:
              - "es:ESHttpGet"
              - "es:ESHttpPost"
              - "es:ESHttpPut"
              - "es:DescribeElasticsearchDomain"
            Resource: 
              - !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/logs-domain"
              - !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/logs-domain/*"
          - Effect: Allow
            Principal: "*"
            Action: 
              - "es:ESHttpGet"
              - "es:ESHttpPost"
            Resource:
              - !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/logs-domain"
              - !Sub "arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/logs-domain/*"
            Condition:
              IpAddress: 
                aws:SourceIp: "41.76.192.17/32"

Outputs:
  OpenSearchDomainEndpoint:
    Value: !GetAtt OpenSearchDomain.DomainEndpoint

  OpenSearchDomainArn:
    Value: !GetAtt OpenSearchDomain.Arn

  OpenSearchDomainName:
    Value: !Ref OpenSearchDomain




