AWSTemplateFormatVersion: 2010-09-09

Resources:

  OpenSearchUsernameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /OpenSearch/Username
      Type: String
      Value: admin

  OpenSearchPasswordParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /OpenSearch/Password
      Type: String
      Value: Admin123$

  CWAgentConfigParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /CloudWatch/AgentConfig
      Type: String
      Value: |
        {
          "agent": {
            "metrics_collection_interval": 60,
            "logfile": "/opt/aws/amazon-cloudwatch-agent/logs/agent.log"
          },
          "logs": {
            "logs_collected": {
              "files": {
                "collect_list": [
                  {
                    "file_path": "/var/log/app.log",
                    "log_group_name": "application-logs",
                    "log_stream_name": "{instance_id}"
                  }
                ]
              }
            }
          }
        }




