AWSTemplateFormatVersion: "2010-09-09"

Resources:

  EC2Stack:
    DependsOn:
      - CloudWatchStack
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iac-bucket-azamcloud.s3.us-east-1.amazonaws.com/ec2.yaml
      
  CloudWatchStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iac-bucket-azamcloud.s3.us-east-1.amazonaws.com/cloudwatch.yaml

  SsmStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iac-bucket-azamcloud.s3.us-east-1.amazonaws.com/ssm.yaml

  OpenSearchStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iac-bucket-azamcloud.s3.us-east-1.amazonaws.com/opensearch.yaml
      Parameters:
        OpenSearchLogGroup: !GetAtt CloudWatchStack.Outputs.OpenSearchLogGroupArn
        FirehoseLogGroup: !GetAtt CloudWatchStack.Outputs.FirehoseLogGroupName

  FirehoseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iac-bucket-azamcloud.s3.us-east-1.amazonaws.com/firehose.yaml
      Parameters:
        OpenSearchDomain: !GetAtt OpenSearchStack.Outputs.OpenSearchDomainName
        FirehoseLogGroup: !GetAtt CloudWatchStack.Outputs.FirehoseLogGroupName
        FirehoseLogStream: !GetAtt CloudWatchStack.Outputs.FirehoseLogStreamName
        OpenSearchFirehoseRole: !GetAtt OpenSearchStack.Outputs.OpenSearchFirehoseRoleArn
        FirehoseTransformLambdaName: !GetAtt LambdaStack.Outputs.FirehoseTransformLambdaFunctionName
        FirehoseTransformLambdaArn: !GetAtt LambdaStack.Outputs.FirehoseTransformLambdaFunctionArn

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://iac-bucket-azamcloud.s3.us-east-1.amazonaws.com/Lambda.yaml
      Parameters:
        LambdaLogGroup: !GetAtt CloudWatchStack.Outputs.LambdaLogGroupName
        FirehoseArn: !GetAtt FirehoseStack.Outputs.FirehoseArn
        ApplicationLogGroup: !GetAtt CloudWatchStack.Outputs.
        FirehoseStreamName: !GetAtt FirehoseStack.Outputs.



    






